# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

gems: [jekyll-paginate,jekyll-gist]

# Setup
title:            Shiyang Ao
tagline:          'Game Programmer Portfolio'
description:      'Game Programmer Portfolio Site'
url:              https://aosyang.github.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aosyang/aosyang.github.io
