# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

gems: [jekyll-paginate,jekyll-gist]

# Setup
title:            Shiyang Ao
tagline:          'Game Programmer Portfolio'
description:      'Game programmer portfolio site'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aosyang/aosyang.github.io
